CREATE DATABASE lzx2005;

use lzx2005;

CREATE TABLE lzx2005(
`user_id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',
`username` VARCHAR(20) NOT NULL COMMENT '用户名',
`password` VARCHAR(120) NOT NULL COMMENT '密码',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`user_type` tinyint NOT NULL DEFAULT 1 COMMENT '用户类型，管理员0，普通用户1',
PRIMARY KEY(user_id)
)ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='用户表';


CREATE TABLE blog(
`blog_id` bigint NOT NULL AUTO_INCREMENT COMMENT '文章ID',
`title` VARCHAR(30) NOT NULL COMMENT '文章标题',
`content` text NOT NULL COMMENT '文章正文',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`view` bigint NOT NULL DEFAULT 0 COMMENT '浏览量',
`blog_type` tinyint NOT NULL DEFAULT 0 COMMENT '文章类型,普通0',
PRIMARY KEY(blog_id)
)ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT='博客列表';